# Source: github.com/claude-code-book/spinner-verbs-dictionary (CC BY-NC-SA 4.0)
# Modifications: removed "Clauding", added "Yarning".
THINKING_VERBS = [
    "Actualizing", "Brewing", "Puzzling", "Spinning", "Precipitating",
    "Tomfoolering", "Creating", "Philosophising", "Pollinating", "Bootstrapping",
    "Unravelling", "Burrowing", "Crunching", "Sussing", "Photosynthesizing",
    "Considering", "Zesting", "Gitifying", "Vibing", "Flummoxing",
    "Yarning", "Cascading", "Envisioning", "Coalescing", "Flambéing",
    "Musing", "Gallivanting", "Concocting", "Flibbertigibbeting", "Galloping",
    "Schlepping", "Discombobulating", "Determining", "Grooving", "Spelunking",
    "Enchanting", "Roosting", "Symbioting", "Newspapering", "Germinating",
    "Jitterbugging", "Scurrying", "Accomplishing", "Propagating", "Calculating",
    "Hashing", "Manifesting", "Sketching", "Scheming", "Undulating",
    "Stewing", "Crystallizing", "Improvising", "Dilly-dallying", "Ideating",
    "Recombobulating", "Incubating", "Orbiting", "Nebulizing", "Sublimating",
    "Architecting", "Shenaniganing", "Beaming", "Nucleating", "Inferring",
    "Smooshing", "Pouncing", "Jiving", "Evaporating", "Hullaballooing",
    "Nesting", "Mustering", "Scampering", "Contemplating", "Caramelizing",
    "Processing", "Twisting", "Generating", "Misting", "Quantumizing",
    "Honking", "Combobulating", "Whirring", "Moonwalking", "Embellishing",
    "Synthesizing", "Baking", "Razzle-dazzling", "Whirlpooling", "Deliberating",
    "Topsy-turvying", "Proofing", "Thundering", "Slithering", "Noodling",
    "Razzmatazzing", "Puttering", "Waddling", "Tinkering", "Shimmying",
    "Metamorphosing", "Harmonizing", "Cerebrating", "Simmering", "Imagining",
    "Bloviating", "Ionizing", "Wibbling", "Lollygagging", "Cooking",
    "Julienning", "Sprouting", "Divining", "Doodling", "Seasoning",
    "Doing", "Orchestrating", "Infusing", "Ruminating", "Beboppin'",
    "Drizzling", "Booping", "Perusing", "Computing", "Percolating",
    "Boogieing", "Reticulating", "Hustling", "Frolicking", "Transmuting",
    "Canoodling", "Ebbing", "Meandering", "Hyperspacing", "Catapulting",
    "Moseying", "Conjuring", "Shucking", "Prestidigitating", "Boondoggling",
    "Gusting", "Levitating", "Marinating", "Churning", "Mulling",
    "Whatchamacalliting", "Zigzagging", "Kneading", "Warping", "Cultivating",
    "Thinking", "Leavening", "Whisking", "Deciphering", "Actioning",
    "Herding", "Swirling", "Pondering", "Forging", "Osmosing",
    "Wrangling", "Elucidating", "Sock-hopping", "Pontificating", "Tempering",
    "Sautéing", "Frosting", "Fermenting", "Choreographing", "Billowing",
    "Blanching", "Perambulating", "Swooping", "Channelling", "Skedaddling",
    "Wizarding", "Cogitating", "Crafting", "Forming", "Garnishing",
    "Hatching", "Befuddling", "Composing", "Unfurling",
]
